image: Visual Studio 2017
version: '{build}'
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
assembly_info:
  patch: false
install:
  - choco install gitversion.portable -pre -y
before_build:
  - gitversion /l console /output buildserver
  - msbuild /t:Restore src/Serilog.Enricher.MassTransit.sln
build_script:
  - msbuild /t:Build src/Serilog.Enricher.MassTransit.sln /p:PackageVersion=%GitVersion_NuGetVersionV2% /p:AssemblyVersion=%GitVersion_AssemblySemVer% /p:InformationalVersion=%GitVersion_InformationalVersion%
after_build:
  - msbuild /t:Pack src/Serilog.Enricher.MassTransit.sln /p:PackageVersion=%GitVersion_NuGetVersionV2% /p:AssemblyVersion=%GitVersion_AssemblySemVer% /p:InformationalVersion=%GitVersion_InformationalVersion%
