image: Visual Studio 2017
version: '{build}'
configuration: Release
platform: Any CPU
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
assembly_info:
  patch: false
install:
  - choco install gitversion.portable -pre -y
before_build:
  - gitversion /l console /output buildserver
  - msbuild /t:Restore src/Serilog.Enrichers.MassTransit.sln
build_script:
  - msbuild /t:Build src/Serilog.Enrichers.MassTransit.sln /p:PackageVersion=%GitVersion_NuGetVersion% /p:AssemblyVersion=%GitVersion_AssemblySemVer% /p:InformationalVersion=%GitVersion_InformationalVersion%
after_build:
  - msbuild /t:Pack src/Serilog.Enrichers.MassTransit.sln /p:PackageVersion=%GitVersion_NuGetVersion% /p:AssemblyVersion=%GitVersion_AssemblySemVer% /p:InformationalVersion=%GitVersion_InformationalVersion%
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/serilog-enrichers-masstransit/api/v2/package
    api_key:
      secure: kkg+HqHSBSZIZkTeW+fe6l7Ae1WMb60aXKUqEsn/aQSKoyuzRyN6195nDKpyFgx7
    artifact: /.*\.symbols\.nupkg/