install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - msbuild /t:Restore src/Serilog.Enricher.MassTransit.sln

build:
  - msbuild /t:Build src/Serilog.Enricher.MassTransit.sln

after_build:
  - msbuild /t:Pack src/Serilog.Enricher.MassTransit.sln