install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - msbuild /t:Restore src/Serilog.Enrichers.MassTransit.sln

build:
  - msbuild /t:Build src/Serilog.Enrichers.MassTransit.sln

after_build:
  - cmd: ECHO msbuild /T:Package <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
