install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - msbuild /t:Restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: src/Serilog.Enricher.MassTransit.sln

after_build:
  - cmd: ECHO msbuild /T:Package <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
